### ISSUE TITLE
docker-compose does not complete

### ISSUE THREAD

**Issue by goedelsoup** [underarmour/estate#1]
Branch: master
OS: OSX v10.12.6
Docker: 17.06.1-ce-mac24

Get the following response when running `docker-compose build dev` from the project root as described in the readme:
```
Step 15/16 : RUN webpack --bail --config webpack/webpack.prod.config.js && django-admin collectstatic --noinput
 ---> Running in 84d9e7e57ea5
Hash: 7ee92da4ee65dedfe9a2
Version: webpack 2.4.1
Time: 5141ms
                       Asset     Size  Chunks                    Chunk Names
main-7ee92da4ee65dedfe9a2.js  3.93 MB       0  [emitted]  [big]  main
   [1] ./~/react/react.js 56 bytes {0} [built]
  [10] ./~/react-dom/index.js 59 bytes {0} [built]
  [22] ./~/react-redux/es/index.js 194 bytes {0} [built]
  [31] ./~/react-router-dom/es/index.js 925 bytes {0} [built]
  [64] ./~/axios/index.js 40 bytes {0} [built]
 [126] ./~/redux/es/index.js 1.08 kB {0} [built]
 [219] ./estate/assets/js/reducers/index.js 501 bytes {0} [built]
 [220] ./~/js-yaml/index.js 81 bytes {0} [built]
 [221] ./~/react-hot-loader/index.js 41 bytes {0} [built]
 [222] ./~/react-hot-loader/patch.js 41 bytes {0} [built]
 [223] ./~/redux-localstorage/lib/persistState.js 3.13 kB {0} [built]
 [224] ./estate/assets/js/estate.css 1.18 kB {0} [built]
 [262] ./estate/assets/js/index.jsx 2.18 kB {0} [built]
 [573] ./~/react-router-dom/es/matchPath.js 52 bytes {0} [built]
 [574] ./~/react-router-dom/es/withRouter.js 53 bytes {0} [built]
    + 612 hidden modules
Traceback (most recent call last):
  File "/usr/local/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/service/estate/settings/__init__.py", line 7, in <module>
    from .storages import * # NOQA
ImportError: No module named storages
ERROR: Service 'dev' failed to build: The command '/bin/sh -c webpack --bail --config webpack/webpack.prod.config.js && django-admin collectstatic --noinput' returned a non-zero code: 1
```

**Comment by rocktavious** [comment]
@goedelsoup Thank you for your interest in this project - I suspect there is just a missing django dependency not being installed in the dockerfile - I will submit a PR for this later this week (i can't right now though because AWS S3 is down)

**Comment by rocktavious** [comment]
@goedelsoup I have pushed a fix into the master branch of this repo that should fix the issue.  Please let me know if you are still having issues - FWIW this repo is still a WIP and I will continue to make progress on getting this into a state that is ready to be used, but right now it may not be.
